```{dot}
//| label: fig-country_capital_rel
//| fig-cap: One to One Example
//| fig-height: 1.5
digraph G {
rankdir = "LR";
node [shape=plaintext];
splines=polyline;
edge [minlen=1.5];

subgraph cluster_0 {
color=white;
rank=same;
Table1 [label=<
<table border="1" cellborder="0" cellspacing="0">
<tr><td bgcolor="lightblue"><b>Country</b></td></tr>
<tr><td PORT="row11">China</td></tr>
<tr><td PORT="row12">France</td></tr>
<tr><td PORT="row13">Italy</td></tr>
</table>
>];
}
 



subgraph cluster_1 {
color=white;
rank=same;
Table2 [label=<
<table border="1" cellborder="0" cellspacing="0">
<tr><td bgcolor="lightblue"><b>Capital</b></td></tr>
<tr><td PORT="row21">Beijing</td></tr>
<tr><td PORT="row22">Paris</td></tr>
<tr><td PORT="row23">Rome</td></tr>
</table>
>];
}

Table1:row11:e -> Table2:row21:w;
Table1:row12:e -> Table2:row22:w;
Table1:row13:e -> Table2:row23:w;

}
```
```{dot}
//| label: fig-professor_class_rel
//| fig-cap: One to Many Example
//| fig-height: 1.5
digraph G {
rankdir = "LR";
node [shape=plaintext];
splines=polyline;
edge [minlen=1.5];

subgraph cluster_0 {
color=white;
rank=same;
Table1 [label=<
<table border="1" cellborder="0" cellspacing="0">
<tr><td bgcolor="lightblue"><b>Professor</b></td></tr>
<tr><td PORT="row11">Hobbs</td></tr>
<tr><td PORT="row12">Doe</td></tr>
</table>
>];
}
 



subgraph cluster_1 {
color=white;
rank=same;
Table2 [label=<
<table border="1" cellborder="0" cellspacing="0">
<tr><td bgcolor="lightblue"><b>Class</b></td></tr>
<tr><td PORT="row21">690-02</td></tr>
<tr><td PORT="row22">692-01</td></tr>
<tr><td PORT="row23">405-01</td></tr>
</table>
>];
}

Table1:row11:e -> Table2:row21:w;
Table1:row12:e -> Table2:row22:w;
Table1:row11:e -> Table2:row23:w;
}
```
```{dot}
//| label: fig-student_class_rel
//| fig-cap: Many to Many Example
//| fig-height: 1.5
digraph G {
rankdir = "LR";
node [shape=plaintext];
splines=polyline;
edge [minlen=1.5];

subgraph cluster_0 {
color=white;
rank=same;
Table1 [label=<
<table border="1" cellborder="0" cellspacing="0">
<tr><td bgcolor="lightblue"><b>Student</b></td></tr>
<tr><td PORT="row11">John</td></tr>
<tr><td PORT="row12">David</td></tr>
<tr><td PORT="row13">Celeste</td></tr>
</table>
>];
}


subgraph cluster_1 {
color=white;
rank=same;
Table2 [label=<
<table border="1" cellborder="0" cellspacing="0">
<tr><td bgcolor="lightblue"><b>Class</b></td></tr>
<tr><td PORT="row21">690-02</td></tr>
<tr><td PORT="row22">692-01</td></tr>
<tr><td PORT="row23">405-01</td></tr>
</table>
>];
}


Table1:row11:e -> Table2:row21:w [color=red];
Table1:row11:e -> Table2:row22:w [color=red];

Table1:row12:e -> Table2:row21:w [color=blue];
Table1:row12:e -> Table2:row22:w [color=blue];
Table1:row12:e -> Table2:row23:w [color=blue];

Table1:row13:e -> Table2:row22:w [color=orange];
Table1:row13:e -> Table2:row23:w [color=orange];


}
```
```{r include= FALSE}
library(dplyr)

employees <- data.frame(
  employee_id = c(1, 2, 3, 4, 5),
  name = c("John", "Jane", "Bob", "Alice", "Tom")
)

projects <- data.frame(
  project_id = c(1, 2, 3, 4, 5, 6),
  employee_id = c(1, 2, 3, 1, 4, 6)
)
```
```{r}
#| layout-ncol: 2
knitr::kable(employees, caption = "Employees Table")
knitr::kable(projects, caption = "Projects Table")
```
```{r}
left_join_result <- employees %>%
  left_join(projects, by = "employee_id")
```
```{r}
#| echo: false
knitr::kable(left_join_result, caption = "Result of Left Join")
```
```{r}
right_join_result <- employees %>%
  right_join(projects, by = "employee_id")
```
```{r}
#| echo: false
knitr::kable(right_join_result, caption = "Result of Right Join")
```
```{r}
full_join_result <- employees %>%
  full_join(projects, by = "employee_id")
```
```{r}
#| echo: false
knitr::kable(full_join_result, caption = "Result of Full Join")
```
```{r}
inner_join_result <- employees %>%
  inner_join(projects, by = "employee_id")
```
```{r}
#| echo: false
knitr::kable(inner_join_result, caption = "Result of Inner Join")
```
```{r, results='hide'}
anti_join_result <- employees %>%
  anti_join(projects, by = "employee_id")
# knitr::kable(anti_join_result, caption = "Result of Anti Join")
```
```{r, echo = FALSE}
knitr::kable(anti_join_result, caption = "Result of Anti Join")
```
```{r}
semi_join_result <- employees %>%
  semi_join(projects, by = "employee_id")
```
```{r}
#| echo: false
knitr::kable(semi_join_result, caption = "Result of Semi Join")
```
