```{r include=FALSE}
library("tidyverse")
# Set print option for tibble to be 5
options(pillar.print_min = 5)
```
```{css, echo = FALSE}
.output {
max-height: 300px;
overflow-y: scroll;
}
```
```{r}
# A "#" is used to annotate comments!
2 + 2
2 * 4
2^8
(1 + 3) / (3 + 5)
log(10) # Calculates the natural log of 10!
```
```{r}
x <- 2 # Equivalent to x = 2
x * 4
```
```{r}
x
x <- x * 5
```
```{r}
x
class(x)
```
```{r}
(true_or_false <- TRUE) # Wrapping with (...) prints the variable
class(true_or_false)
```
```{r}
(name <- "Parsa Rahimi")
class(name)
```
```{r}
(name_surname <- c("Parsa", "Rahimi"))
length(name)
length(name_surname)
```
```{r}
(i <- c(1, 2, 3, 4))
i + 10 # Adds 10 to each element
i * 10 # Multiplies each element by 10
# Adds together elements in corresponding positions
i + c(2, 4, 6, 8)
```
```{r}
name
name <- i + c(5, 4, 2, 1)
name
```
```{r error = TRUE}
name_surname + 2
str(name_surname)
```
```{r}
#| echo: true
library(tidyverse)
```
```{r cache = TRUE}
# Download data from GitHub
data <- readr::read_csv(
  "https://raw.githubusercontent.com/nikitoshina/quarto_book/main/mexico_sample_data.csv"
)
```
```{r}
#| classes: output
data %>% glimpse()
```
```{r}
data_raven <- data %>% select(
  id, mean_temp_celsius, gender, pr_correct,
  tr_correct, ch_tournament, ch_correct
)
tail(data_raven)
```
```{r}
data_raven %>%
  select(-gender) %>% # Selects all columns except 'gender'
  head() # Displays the first few rows
```
```{r}
data_male <- data_raven %>% filter(gender == "Male")
data_female <- data_raven %>% filter(gender == "Female")
head(data_male)
head(data_female)
```
```{r}
data_raven %>%
  filter(
    (gender == "Male" & mean_temp_celsius > 30) | (gender == "Female" & mean_temp_celsius < 30)
  )
```
```{r}
data_raven %>%
  arrange(pr_correct)
```
```{r}
data_raven %>%
  arrange(desc(pr_correct))
```
```{r}
#| classes: output
tibble(rows = 1:4) %>% mutate(
  One = 1,
  Comment = "Something",
  Approved = TRUE
)
```
```{r}
data_raven %>% mutate(
  mean_temp_fahrenheit = (mean_temp_celsius * 9 / 5) + 32,
  improvement = tr_correct - pr_correct,
  pr_deviation = pr_correct - mean(pr_correct),
  .keep = "none" # keep only newly created columns
)
```
```{r}
data_raven <- data_raven %>%
  mutate(gender = case_match(gender, "Male" ~ "M", "Female" ~ "F"))
```
```{r}
data_raven %>%
  summarize(
    prop_male = sum(gender == "M", na.rm = TRUE) / n(),
    pr_median = median(pr_correct),
    tr_max = max(tr_correct),
    ch_ratio = sum(ch_tournament) / n(),
    ch_mean = mean(ch_correct)
  )
```
```{r}
data_raven %>%
  drop_na(gender) %>%
  group_by(gender) %>%
  summarize(
    pr_mean = mean(pr_correct),
    tr_mean = mean(tr_correct),
    ch_mean = mean(ch_correct),
    pr_sd = sd(pr_correct),
    n = n()
  )
```
```{r}
data_raven %>%
  drop_na(gender) %>%
  group_by(gender, ch_tournament) %>%
  summarize(
    ch_mean = mean(ch_correct),
    pr_sd = sd(ch_correct),
    n = n()
  )
```
```{r}
data_raven %>%
  drop_na(gender) %>%
  group_by(gender) %>%
  mutate(n = n()) %>%
  summarize(mean_male = mean(gender == "M")) %>%
  ungroup()
```
```{r}
data_raven %>%
  drop_na(gender) %>%
  group_by(gender) %>%
  mutate(n = n()) %>%
  ungroup() %>%
  summarize(mean_male = mean(gender == "M"))
```
```{r}
#| output: false
data_raven %>%
  drop_na(gender) %>%
  # same as `group_by %>% mutate %>% ungroup`
  mutate(n = n(), .by = gender) %>%
  summarize(mean_male = mean(gender == "M"))
```
```{r}
(df <- tibble(
  x = list(1, 2:3, 4:6, 7:11)
))
```
```{r}
df %>% mutate(length = length(x))
```
```{r}
df %>%
  rowwise() %>%
  mutate(length = length(x))
```
```{r}
data_raven %>% count(gender)
```
```{r}
data_raven %>% count(gender, ch_tournament)
```
```{r}
data_raven %>%
  rename(subject_id = id, sex = gender)
```
```{r}
data_raven %>%
  select(-id) %>%
  mutate(id = row_number()) %>%
  relocate(id)
```
```{r}
#| column: body-outset-left
library(skimr)
skim(data_raven)
```
```{r}
library(lubridate)
day_year_month <- "31/2001/01"
(date <- dym(day_year_month))

month_day_year_hour_minute <- "Jan 31st 2001 6:05PM"
(date_time <- mdy_hm(month_day_year_hour_minute))

sentence_with_date <- "Elizabeth II was Queen of the United Kingdom from 6 February 1952."
# Impressive, isn't it? `lubridate` can identify the date within text
# and parse it for you!
dmy(sentence_with_date)
```
```{r}
day(date_time)
hour(date_time)
# Setting `label = TRUE` provides the month's name, while `abbr =
# FALSE` yields the full name.
month(date_time, label = TRUE, abbr = FALSE)
```
