```{r include = F}
library(datasauRus)
library(tidyverse)
library(patchwork)
library(gridExtra)
knitr::opts_chunk$set(echo = T, warning = F, message = F, error = F)
data_raven <- readr::read_csv(
  "https://raw.githubusercontent.com/nikitoshina/quarto_book/main/raven_data.csv"
  )
```
```{r echo = FALSE}
datasaurus_dozen %>%
  group_by(dataset) %>%
  summarize(
    mean_x = round(mean(x), 2),
    mean_y = round(mean(y), 2),
    std_dev_x = round(sd(x), 2),
    std_dev_y = round(sd(y), 2),
    corr_x_y = round(cor(x, y), 2)
  ) %>%
  filter(dataset == "dino") %>%
  select(-dataset) %>%
  kableExtra::kable()
```
```{r}
#| label: fig-datasaurus_dozen
#| code-fold: true
#| code-summary: "Show the code"

datasauRus::datasaurus_dozen %>%
  filter(dataset %in% c("away", "dino", "star")) %>%
  mutate(dataset = str_to_upper(dataset)) %>%
  ggplot(aes(x = x, y = y, colour = dataset)) +
  geom_point() +
  theme_void(base_size = 18) +
  theme(
    legend.position = "none",
    strip.text = element_text(face = "bold")
  ) +
  facet_wrap(~dataset, ncol = 3) +
  coord_fixed(ratio = 0.8)
```
```{r}
#| label: fig-explanatory_graph
old_pc_fun <- function(x) (x - 0.9)^(1 / 3)
inv_old_pc_fun <- function(y) y^3 + 0.9
new_pc_fun <- function(x) (x - 0.9)^(1 / 1.5) + 1
inv_new_pc_fun <- function(y) (y - 1)^(1.5) + 0.9
line_fun_h <- function(x, const) {
  old_y <- old_pc_fun(const)
  new_x <- inv_new_pc_fun(old_y)
  old_x <- const
  out <- if_else(!between(x, new_x, old_x), NA, old_y)
  return(out)
}



old_y <- old_pc_fun(4)
new_x <- inv_new_pc_fun(old_y)

plot <- ggplot() +
  geom_function(fun = \(x) if_else(!between(x, 1, 3), NA, new_pc_fun(x)), color = "black", linewidth = 2) +
  geom_function(fun = \(x) if_else(!between(x, 1, 5), NA, old_pc_fun(x)), color = "lightgrey", linewidth = 1) +
  geom_segment(aes(x = new_x, y = old_y, xend = 4, yend = old_y),
    linetype = 3,
    color = "black",
    linewidth = 1
  ) +
  geom_segment(aes(x = new_x, y = old_pc_fun(new_x), xend = new_x, yend = old_y),
    linetype = 3,
    color = "black",
    linewidth = 1
  ) +
  geom_segment(aes(x = new_x, y = 0.5, xend = new_x, yend = old_pc_fun(new_x)),
    color = "lightgrey",
    linetype = 3,
    linewidth = 1
  ) +
  xlim(0.9, 4) +
  ylim(0.4, 3) +
  geom_text(aes(x = new_x, y = 0.45, label = "13W"),
    hjust = 0.5,
    vjust = 1,
    color = "black",
    family = "mono",
    face = "bold",
    size = 14 / .pt
  ) +
  geom_text(aes(x = 4 - .02, y = old_y + 0.05, label = "other chips"),
    hjust = 1, vjust = 0,
    family = "mono",
    color = "black",
    face = "bold",
    size = 14 / .pt
  ) +
  geom_text(aes(x = 2.7, y = 2.6, label = "P100 chip"),
    hjust = 1, vjust = 0,
    family = "mono",
    color = "black",
    face = "bold",
    size = 18 / .pt
  ) +
  theme_void() +
  theme(
    axis.title.x = element_text(
      family = "mono", size = 16, colour = "darkgrey", face = "bold", vjust = 0.5, hjust = 0.9,
      margin = margin(5, 0, 5, 0)
    ),
    axis.title.y = element_text(family = "mono", size = 16, colour = "darkgrey", face = "bold", vjust = 0.5, hjust = 0.9, angle = 90, margin = margin(0, 5, 0, 5)),
    axis.line = element_line(color = "lightgrey", linewidth = 1),
  ) +
  labs(
    x = "power consumption lower is better",
    y = "chip performance hihger is better"
  )

plot
# ggsave("~/Downloads/fig-explanatory-graph.pdf", plot, height = 5, width = 8)
```
```{r}
#| label: fig-scatter_bar_plots
#| code-fold: true
#| code-summary: "Show the code"
point_plot <- data_raven %>%
  count(pr_correct, name = "count") %>%
  ggplot(aes(x = pr_correct, y = count)) +
  geom_point(size = 3) +
  theme_minimal()
col_plot <- data_raven %>%
  count(pr_correct, name = "count") %>%
  ggplot(aes(x = pr_correct, y = count)) +
  geom_col() +
  theme_minimal()
point_plot + col_plot
```
```{r}
#| label: fig-piece_rate_plot
# Count occurrences of each `pr_correct` value and calculate their percentages
count_data <- count(data_raven, pr_correct) %>% mutate(perc = n/sum(n))
  
# Plotting the distribution of correct answers
count_plot <- count_data %>%
  ggplot(aes(x = as.factor(pr_correct), y = perc)) + # Mapping `pr_correct` as factor to x and its percentage to y
  geom_col(fill = "steelblue") + # Create bars with steelblue color
  geom_text(data = filter(count_data, n > 3), aes(label = n, y = perc), nudge_y = -0.02, color = "white", fontface = "bold", size = 12/.pt) + # Add labels to bars if count > 3
  theme_minimal(base_size = 12) + # Use minimal theme with base size 16 for aesthetics
  theme(
    panel.grid = element_blank(), # Remove gridlines
    panel.grid.major.y = element_line(linewidth = 0.5, linetype = 2, color = "darkgrey"), # Style major y gridlines
    axis.title = element_text(color = "darkgrey"), # Style axis titles
    plot.title.position = "plot" # Position the title inside the plot area
  ) +
  scale_y_continuous(labels = scales::label_percent(), expand = c(0,0,0.1,0)) + # Format y axis as percentage
  scale_x_discrete(expand = c(0,0,0,0)) + # Control expansion of x axis
  labs(
    x = "Number of Correct Answers", # X axis label
    y = "Percentage of Total", # Y axis label
    title = "Distribution of Correct Answers in Piece-rate Game" # Chart title
  )

count_plot

ggsave(plot = count_plot, filename = "../count_plot.pdf",height = 2.5, width =4.6)
```
```{r echo = F}
   head(iris)
```
```{r}
#| label: fig-data_layer
   data_layer <- ggplot(data = iris)
   data_layer
```
```{r}
#| label: fig-aes_layer
   aes_layer <- ggplot(
     data = iris,
     aes(x = Sepal.Length, y = Sepal.Width)
   )
   aes_layer
   aes_layer$mapping
```
```{r}
#| label: fig-geometry_layer
   geometry_layer <- aes_layer + geom_point()
   geometry_layer
```
```{r}
#| label: fig-scales_layer
   scales_layer <- ggplot(data = iris, aes(x = Sepal.Length, y = Sepal.Width, color = Species)) +
     geom_point() +
     scale_color_manual(values = c("red", "orange", "pink"))
   scales_layer
   scales_layer$mapping
```
```{r}
#| label: fig-stat_layer
   stat_layer <- ggplot(data = iris, aes(x = Sepal.Length)) +
     geom_histogram(bins = 20, color = "white")
   stat_layer
```
```{r}
#| label: fig-facets_layer
   facets_layer <- geometry_layer + facet_wrap(vars(Species), ncol = 3)
   facets_layer
```
```{r}
#| label: fig-theme_layer
theme_layer <- facets_layer + 
  # Apply a minimal theme with a base font size of 18
  theme_minimal(base_size = 18) + 
  # Add points with size 2 and color coral
  geom_point(size = 2, color = "#ffb86c") + 
  # Customize the theme settings
  theme(
    # Set plot background color to dark gray and border color to gray
    plot.background = element_rect(fill = "#282a36", color = "#44475A"),
    # Remove minor grid lines
    panel.grid.minor = element_blank(),
    # Set major grid lines color to gray
    panel.grid.major = element_line(colour = "#44475a"),
    # Set axis text and title as well as facet strip text color to white
    axis.text = element_text(color = "#f8f8f2"),
    axis.title = element_text(color = "#f8f8f2"),
    strip.text = element_text(color = "#f8f8f2")
  ) + 
  # Add labels for the x and y axes
  labs(x = "Sepal Length", y = "Sepal Width") + 
  # Set the x-axis limits from 4 to 8
  xlim(4, 8)

# Return the modified theme_layer
theme_layer

ggsave("~/Downloads/theme_layer.pdf", theme_layer, height = 3.4, width = 5.4)
```
```{r}
#| eval: false
# install.packages('esquisse')
library(esquisse)
esquisser(iris)
```
```{r}
# install.packages("ggThemeAssist")
library(ggThemeAssist)
```
```{r}
#| label: fig-ggplotly
library(plotly) # Load the necessary libraries.
library(ggplot2)

p <- ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, color = Species)) +
geom_point(size = 1, alpha = 1) +
# Create a scatter plot using `ggplot2`. The plot is of Sepal Length
# against Sepal Width, with data points colored by Species and sized
# by Petal Length.
theme_minimal()

# Convert the `ggplot2` plot to a `plotly` plot using the `ggplotly`
# function.
pp <- ggplotly(p)

pp # Display the interactive plot.
```
```{r, eval=knitr::is_html_output()}
#| label: fig-plotly
library(plotly) # Load the `plotly` library.

# Create a scatter plot using `plot_ly`, where Sepal Length is plotted
# against Sepal Width, and color of points are determined by Species.
p <- plot_ly(
  data = iris,
  x = ~Sepal.Length,
  y = ~Sepal.Width,
  color = ~Species,
  type = "scatter",
  mode = "markers",
  marker = list(size = 6),
  hovertemplate = paste0(
    'Sepal Length: %{x}<br>',
    'Sepal Width: %{y}<br>',
    '<extra></extra>' # This line removes the additional trace info
  )
)

# Customize the plot layout, including the title and axis labels,
# and setting the hover mode to display information about the nearest
# point.
p <- layout(
  p,
  title = "Sepal Measurements",
  xaxis = list(title = "Sepal Length"),
  yaxis = list(title = "Sepal Width")
)

p # Display the plot.
```
```{r, eval=knitr::is_html_output()}
#| label: fig-echarts
library(echarts4r) # Load the `echarts4r` library.

e_chart <- iris %>%
group_by(Species) %>% # Group the data by the Species variable.
# Initialize an Echarts plot with Sepal.Length as the x-axis.
e_charts(Sepal.Length) %>%
# Add a scatter plot to the existing Echarts plot with Sepal.Width as
# the y-axis.
e_scatter(Sepal.Width, symbol_size = 7) %>%
# Set the range for the y-axis (Sepal.Length) from 1.5 to 5.
e_y_axis(min = 1.5, max = 5) %>%
# Set the range for the x-axis (Sepal.Width) from 4 to 8.
e_x_axis(min = 4, max = 8) %>%
e_axis_labels(
x = "Sepal Width",
y = "Sepal Length"
# Label the x-axis as "Sepal Width" and the y-axis as "Sepal Length".
) %>%
# Add a tooltip to the plot that appears when hovering over data
# points and displays both the Sepal Length and Sepal Width.
e_tooltip(
trigger = "item",
formatter = htmlwidgets::JS("
function(params){
return('Sepal Length: ' + params.value[0] + '<br />Sepal Width: ' + params.value[1])
}
")
)

e_chart # Display the plot.
```
