```{r}
#| echo: false
#| warning: false
#| message: false
library(tidyverse)
  options(quarto.max_rows = 5)
```
```{r}
#| code-fold: true
# `tribble()` is a function to create a data frame in a readable
# format
df <- tribble(
~day, ~class, ~student_id, ~present,
1, "English", 1, T,
1, "English", 2, T,
1, "English", 4, T,
1, "Science", 2, T,
2, "Math", 1, T,
2, "Math", 2, T,
2, "Math", 4, T,
2, "English", 4, T,
2, "English", 1, T,
3, "Math", 1, T,
3, "Math", 2, T,
3, "Math", 1, T
)
```
```{r}
#| classes: output
#| echo: false
df
```
```{r}
# Creating a complete dataframe with all possible combinations of
# `student_id` and nested combinations of `day` and `class`
complete_df <- df %>%
complete(
# `full_seq()` generates a sequence of student IDs, using the number
# of unique student IDs as the maximum value
student_id = full_seq(student_id, 1),
# `nesting()` creates only combinations that already exist in the data
nesting(day, class),
# Fills missing attendance data with `FALSE`
fill = list(present = FALSE),
# Limit the `fill` to only the newly created (i.e. previously
# implicit)
explicit = FALSE
) %>%
# Orders the resulting data frame by `day`, `class`, `student_id`, and
# `present`
arrange(day, class, student_id, present)
```
```{r}
#| classes: output
#| echo: false
print(complete_df, n = 100)
```
```{r}
head_na <- function(data, n = 5) {
data %>%
filter(is.na(Ozone)) %>%  # Filter rows with NA in `Ozone`.
select(-Ozone) %>%        # Exclude `Ozone` column from the results.
head(n)                   # Display the first `n` rows.
}
head(airquality)
```
```{r}
#| label: fig-missing_pattern
#| fig-cap: Missing Data
#| fig-height: 3 
#| out-height: 1.5in
# Remove rows with missing values in `Solar.R`.
airquality <- drop_na(airquality, Solar.R)
# `md.pattern` makes a matrix of missing values. `invisible` to only
# show plot, without matrix output.
invisible(mice::md.pattern(airquality))
```
```{r}
#| label: fig-vis_miss
#| fig-cap: vizmiss() Plot
#| fig-height: 4
airquality %>%
  arrange(Month, Day) %>%
  visdat::vis_miss(facet = Month)
```
```{r}
airquality %>%
arrange(Month, Day) %>%
mutate(
# Impute with a fixed value (0 in this case).
imp_fixed = coalesce(Ozone, 0),
Ozone_missing = is.na(Ozone),
# Impute with the mean.
imp_mean = coalesce(Ozone, round(mean(Ozone, na.rm = TRUE), 2)),
# Impute with the median.
imp_median = coalesce(Ozone, median(Ozone, na.rm = TRUE)),
imp_fill = Ozone,
.keep = "used" # Keep only "used" columns.
) %>%
# Fills missing values with the most recent non-missing value above.
fill(imp_fill, .direction = "down") %>%
head_na()
```
```{r}
# KNN imputation using the 'VIM' package
library(VIM)
airquality_knn <- kNN(airquality)

airquality_knn %>%
  slice(which(is.na(airquality$Ozone))) %>%
  select("Ozone") %>%
  head(n=5)
```
```{r}
# Fit a linear regression model
model <- lm(Ozone ~ ., data = airquality)

# Predict missing values
predicted_values <- predict(model, newdata = airquality)

# Replace missing values with predicted values
airquality %>% 
  mutate(
    Ozone = Ozone,
    imp_lm = ifelse(is.na(Ozone), predicted_values, Ozone),
    .keep = "used"
  ) %>% 
  head_na()
```
```{r}
# Install and load the missForest package
library(missForest)

airquality %>%
  mutate(
    Ozone = Ozone,
    imp_forest = missForest(.)$ximp$Ozone,
    .keep = "used"
  ) %>%
  head_na()
```
```{r}
airquality %>%
  mutate(
    Ozone_best = coalesce(Ozone, mean(Ozone,na.rm = T) + 2 *sd(Ozone, na.rm = T)),
    Ozone_worst = coalesce(Ozone, mean(Ozone, na.rm = T) - 2 *sd(Ozone, na.rm = T)),
    .by = Month
  ) %>%
  summarize(
    Ozone_best = round(mean(Ozone_best),0),
    Ozone = round(mean(Ozone, na.rm = T),0),
    Ozone_worst = round(mean(Ozone_worst),0),
    .by = Month
  )
```
```{r}
library(mice)
```
```{r}
mice_impute_ozone <- function(data, method) {
  mice::complete(mice(data, method = method, print = F))$Ozone
}
set.seed(1)
airquality %>% 
  mutate(
  Ozone = Ozone,
  imp_pmm = mice_impute_ozone(., "pmm"),
  imp_pmm2 = mice_impute_ozone(., "pmm"),
  imp_cart = mice_impute_ozone(., "cart"),
  imp_cart2 = mice_impute_ozone(., "cart"),
  imp_lasso = mice_impute_ozone(., "lasso.norm"),
  imp_lasso2 = mice_impute_ozone(., "lasso.norm"),
  .keep = "used" # Keep only the variables used in mutate call
) %>%
head_na()
```
```{r}
# Perform multiple imputation
imp <- mice(airquality, 
            m = 5, # number of complete datasets to generate
            method = "pmm", # specifies method for imputation
            seed = 1337, # set seed for reproducibility
            printFlag = FALSE) # don't print history on console
```
```{r}
# Fit a linear model on each imputed dataset
fit <- with(imp, lm(Ozone ~ Solar.R + Wind + Temp + Month)) # replace y, x1, x2 with your dependent and independent variables

# Pool the results of these models
pool <- pool(fit)
summary(pool)
```
```{r}
library(gtsummary)
tbl_regression(fit)
```
```{r, include=knitr::is_html_output()}
#| echo: false
#| eval: true
set.seed(1)
airquality %>%
  mutate(
    imp_fixed = coalesce(Ozone, 0), # Impute with a fixed value (0 in this case)
    Ozone_missing = is.na(Ozone),
    imp_mean = coalesce(Ozone, round(mean(Ozone, na.rm = TRUE), 2)), # Impute with the mean
    imp_fill = Ozone,
    imp_median = coalesce(Ozone, median(Ozone, na.rm = TRUE)), # Impute with the median
    imp_forest = missForest(.)$ximp$Ozone,
    imp_lm = ifelse(is.na(Ozone), predicted_values, Ozone),
    imp_knn = airquality_knn$Ozone,
    # imp_mlh = airquality_mlh$Ozone,
    imp_pmm = complete(mice(., method = "pmm", printFlag = FALSE))$Ozone,
    imp_cart = complete(mice(., method = "cart", printFlag = FALSE))$Ozone,
    imp_lasso = complete(mice(., method = "lasso.norm", printFlag = FALSE))$Ozone,
    .keep = "used" 
  ) %>%
  fill(imp_fill, .direction = "down") %>% 
  filter(is.na(Ozone)) %>%
  select(-Ozone) %>%
  mutate(across(everything(), ~round(.,1))) %>%
  DT::datatable(
  options = list(pageLength = 10, scrollX = TRUE), 
  rownames = FALSE, 
  class = 'cell-border stripe' 
)
```
```{r, include=knitr::is_latex_output()}
mice_impute_ozone <- function(data, method) {
  mice::complete(mice(data, method = method, print = FALSE))$Ozone
}
set.seed(1)
airquality %>%
  mutate(
    # Impute with a fixed value (0 in this case)
    imp_fixed = coalesce(Ozone, 0),
    Ozone_missing = is.na(Ozone),
    # Impute with the mean
    imp_mean = coalesce(
      Ozone,
      round(mean(Ozone, na.rm = TRUE), 2)
    ),
    imp_fill = Ozone,
    # Impute with the median
    imp_median = coalesce(
      Ozone,
      median(Ozone, na.rm = TRUE)
    ),
    imp_forest = missForest(.)$ximp$Ozone,
    imp_lm = ifelse(is.na(Ozone), predicted_values, Ozone),
    imp_knn = airquality_knn$Ozone,
    imp_pmm = mice_impute_ozone(., "pmm"),
    imp_cart = mice_impute_ozone(., "cart"),
    imp_lasso = mice_impute_ozone(., "lasso.norm"),
    .keep = "used"
  ) %>%
  fill(imp_fill, .direction = "down") %>%
  filter(is.na(Ozone)) %>%
  select(-Ozone) %>%
  mutate(across(everything(), ~ round(., 1))) %>%
  gt::gt()
```
