```{r include = FALSE}
library(tidyverse)
library(gapminder)
library(patchwork)
library(ggbeeswarm)
library(ggdist)
library(gghalves)
library(ggwaffle)
library(directlabels)
library(treemapify)
```
```{r}
#| label: fig-top5_countries
plot_top5 <- gapminder %>%
  filter(year == 1997) %>%
  slice_max(gdpPercap, n = 5) %>%
  ggplot(aes(x = fct_reorder(country, gdpPercap, .desc = T), y = gdpPercap)) +
  geom_col(fill = "steelblue") +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = NULL, title = "Top 5 countries by GDP per Capita in 1997") +
  geom_text(aes(label = round(gdpPercap, 0)), vjust = 2, color = "white", size = 4) +
  theme(panel.grid = element_blank(), axis.text.y = element_blank())
plot_top5
ggsave("new_plots/fig-top5_countries.pdf", plot_top5, height = 2, width = 5)
```
```{r barh_data}
barh_data <- tibble(
  Candidate = c(
    "Sadiq Khan", "Shaun Bailey", "Siân Berry",
    "Luisa Porritt", "Niko Omilana", "Laurence Fox", "Brian Rose",
    "Richard Hewison", "Count Binface", "Mandu Reid", "Piers Corbyn",
    "Vanessa Hudson", "Peter Gammons", "Farah London", "David Kurten",
    "Nims Obunge", "Steve Kelleher", "Kam Balayev", "Max Fosh", "Valerie Brown"
  ),
  Percentage = c(
    40.0, 35.3, 7.8, 4.4, 2.0, 1.9,
    1.2, 1.1, 1.0, 0.8, 0.8, 0.7, 0.6, 0.5, 0.4,
    0.4, 0.3, 0.3, 0.2, 0.2
  )
) %>% mutate(is.youtuber = case_when(
  Candidate == "Niko Omilana" ~ 1,
  Candidate == "Max Fosh" ~ 2,
  T ~ 0
))
```
```{r}
#| label: fig-london_bar
london_bar <- barh_data %>%
  ggplot(aes(x = fct_reorder(Candidate, Percentage), y = Percentage, fill = as.factor(is.youtuber))) +
  geom_col() +
  theme_minimal(base_size = 14) +
  coord_flip() +
  labs(x = NULL, y = NULL, title = "London Mayor Elections (2021) by % of Votes") +
  theme(panel.grid = element_blank(),
        legend.position = "none",
        plot.title.position = "plot") +
  scale_y_discrete(expand = c(0, 0, 0, 3)) +
  geom_text(aes(label = Percentage), nudge_y = 0.3, hjust = "left") +
  scale_fill_manual(values = c("#c0bfff", "#f3e408", "#D96161"))

london_bar
ggsave( "new_plots/fig-london_bar.pdf", london_bar, height = 4, width = 5)
```
```{r}
#| label: fig-london_lollipop
london_lollipop <- barh_data %>%
  ggplot(aes(x = fct_reorder(Candidate, Percentage), y = Percentage, color = as.factor(is.youtuber), fill = as.factor(is.youtuber))) +
  geom_segment(aes(
    x = fct_reorder(Candidate, Percentage),
    xend = fct_reorder(Candidate, Percentage),
    y = 0,
    yend = Percentage,
  )) +
  geom_point(shape = 21,size = 2.3, color = "darkgrey") +
  theme_minimal( base_size = 14) +
  coord_flip(clip = "off") +
  labs(x = NULL, y = NULL, title = "London Mayor Elections (2021) by % of Votes") +
  theme(panel.grid = element_blank(), legend.position = "none", plot.title.position = "plot") +
  scale_y_discrete(expand = c(0, 0, 0, 3)) +
  geom_text(aes(label = Percentage), color = "black", nudge_y = 1, hjust = "left") +
  scale_color_manual(values = c("#c0bfff", "#f3e408", "#D96161")) +
  scale_fill_manual(values = c("#c0bfff", "#f3e408", "#D96161"))

london_lollipop
ggsave("new_plots/fig-london_lolipop.pdf", london_lollipop, height = 4, width = 5)
```
```{r}
#| label: fig-bullet_graph
bullet_graph <- ggplot() +
  geom_col(
    aes(x = "NPS", y = 200),
    fill = "#A9A9A9",
    width = 0.6,
    alpha = 0.9
  ) +
  geom_col(
    aes(x = "NPS", y = 170),
    fill = "#808080",
    width = 0.6,
    alpha = 0.9
  ) +
  geom_col(
    aes(x = "NPS", y = 130),
    fill = "#696969",
    width = 0.6,
    alpha = 0.9
  ) +
  geom_col(
    aes(x = "NPS", y = 180),
    fill = "black",
    color = NA,
    width = 0.2
  ) +
  geom_errorbar(
    aes(x = "NPS", ymin = 160, ymax = 160),
    color = "red",
    width = 0.45,
    size = 2
  ) +
  coord_flip() +
  theme_minimal(base_size = 12) +
  labs(
    x = NULL,
    y = NULL,
    title = "Net Promoter Score for 2023",
    subtitle = "We beat the Target!"
  ) +
  theme(
    panel.grid = element_blank(),
    axis.text.x = element_text(size = 8),
    axis.text.y = element_blank()
  ) +
  annotate(
    "text",
    x = c(rep((1 + .45), 3), 0.55),
    y = c(
      130 * 0.5,
      130 + (170 - 130) * 0.5,
      170 + (200 - 170) * 0.5,
      160
    ),
    label = c("Poor", "Good", "Great", "Target"),
    color = c(rep("black", 3), "red")
  ) +
  ylim(c(-100, 100)) +
  scale_y_continuous(breaks = seq(0, 200, 10), labels = seq(-100, 100, 10))

bullet_graph
ggsave("new_plots/fig-bullet_graph.pdf", bullet_graph, height = unit(2.5, "in"), width = unit(5, "in"))
```
```{r}
#| label: fig-distribution
base <- iris %>% ggplot(aes(x = Sepal.Length)) +
  theme_minimal() +
  theme(panel.grid = element_blank(), axis.text.y = element_blank()) +
  coord_cartesian(expand = FALSE, clip = "off") +
  labs(y = NULL, x = NULL)
hist_1 <- base + geom_histogram(fill = "steelblue", color = "white", bins = 6) + labs(subtitle = "6 bins")
hist_2 <- base + geom_histogram(fill = "steelblue", color = "white", bins = 15) + labs(subtitle = "15 bins")
hist_3 <- base + geom_histogram(fill = "steelblue", color = "white", bins = 30) + labs(subtitle = "30 bins")

(hist_1 + hist_2 + hist_3) + plot_annotation(title = "iris Sepal Length Distribution Histograms with Varying Bins")
```
```{r}
#| label: fig-density
base <- iris %>% ggplot(aes(x = Sepal.Length)) +
  theme_minimal() +
  theme(panel.grid = element_blank(), axis.text.y = element_blank()) +
  coord_cartesian(expand = FALSE, clip = "off") +
  labs(y = NULL, x = NULL)
dens_1 <- base + geom_density(color = "steelblue", linewidth = 2, bw = 0.3) + labs(subtitle = "Band Width 0.3")
dens_2 <- base + geom_density(color = "steelblue", linewidth = 2, bw = 0.1) + labs(subtitle = "Band Width 0.1")
dens_3 <- base + geom_density(color = "steelblue", linewidth = 1, bw = 0.03) + labs(subtitle = "Band Width 0.03")

(dens_1 + dens_2 + dens_3) + plot_annotation(title = "iris Sepal Length Distribution Density Plots with Varying Band Widths")
```
```{r}
#| label: fig-frequency
freq_1 <- base + geom_histogram(fill = "grey", color = "white", bins = 15, alpha = 0.5) + geom_freqpoly(color = "steelblue", bins = 15, linewidth = 1.5) + labs(subtitle = "15 bins")

freq_2 <- iris %>% ggplot(aes(x = Sepal.Length)) +
  geom_histogram(aes(fill = Species), position = "dodge", color = "white", bins = 15, alpha = 0.3) +
  geom_freqpoly(aes(color = Species), bins = 15, linewidth = 1.5) +
  labs(subtitle = "15 bins") +
  theme_minimal() +
  theme(
    panel.grid = element_blank(), axis.text.y = element_blank(),
    legend.position = c(.95, .95),
    legend.justification = c("right", "top"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6)
  ) +
  coord_cartesian(expand = FALSE, clip = "off") +
  labs(y = NULL, x = NULL)

freq_1 + freq_2
```
```{r}
set.seed(1337)

group2 <- c(
      rep(0, 5),
      rnorm(30, 10, 3),
      rnorm(60, 25, 3.5),
      rnorm(30, 40, 2)
    )

group2 <- c(group2,
            (100-group2))

data_dist <- tibble(
  group = factor(c(rep("Group 1", 100), rep("Group 2", 250), rep("Group 3", 25))),
  value = c(
    seq(0, 100, length.out = 100),
    group2,
    rep(seq(0, 100, length.out = 5), 5)
  )
) 
```
```{r}
#| label: fig-boxplot
base2 <- iris %>% ggplot(aes(y = Sepal.Length, x = Species)) +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank()) +
  coord_cartesian(expand = FALSE, clip = "off") +
  labs(y = NULL, x = NULL)

box_1 <- base2 + geom_boxplot()

base_dist <- data_dist %>% ggplot(aes(y = value, x = group)) +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank()) +
  coord_cartesian(expand = FALSE, clip = "off") +
  labs(y = NULL, x = NULL)

box_2 <- base_dist + geom_boxplot()
box_3 <- base_dist + geom_boxplot() + geom_point(color = "orange", size = 1.5, alpha = 0.25, position = position_jitter(width = 0.1))

box_1 + box_2 + box_3
```
```{r}
#| label: fig-violin
base2 + geom_violin(draw_quantiles = c(0.25, 0.5, 0.75), bw = 0.15) + geom_jitter(alpha = 0.2, position = position_jitter(width = 0.1))
```
```{r}
#| label: fig-beeswarm
bee_1 <- base2 + geom_beeswarm()
bee_2 <- base_dist + geom_beeswarm()
bee_1 + bee_2
```
```{r}
#| label: fig-raincloud_v
base_dist +
  ggdist::stat_halfeye(
    adjust = .3, # bw
    width = .6,
    .width = 0,
    justification = -.2,
    point_colour = NA
  ) +
  geom_boxplot(
    width = .15,
    outlier.shape = NA
  ) +
  ## add justified jitter from the {gghalves} package
  gghalves::geom_half_point(
    ## draw jitter on the left
    side = "l",
    ## control range of jitter
    range_scale = .4,
    ## add some transparency
    alpha = .3
  ) +
  coord_cartesian(xlim = c(1.2, NA), clip = "off")
```
```{r}
#| label: fig-raincloud_h
base_dist +
  ggdist::stat_halfeye(
    adjust = .3,
    width = .6,
    .width = c(.5, .95),
    justification = -.2,
    point_colour = "black",
  ) +
  geom_half_point(
    ## draw horizontal lines instead of points
    shape = "|",
    side = "l",
    size = 5,
    alpha = .2,
    transformation = position_identity()
  ) +
  coord_cartesian(xlim = c(1.2, NA), clip = "off") + 
  coord_flip()
```
```{r}
#| label: fig-margins
# Load the `ggExtra` package, which provides functions to enhance
# `ggplot2` plots, such as adding marginal histograms.
library(ggExtra)

# Create a base scatter plot of Sepal Length against Sepal Width using
# the `ggplot` function from the `ggplot2` package. The `aes` function
# is used to specify the x and y variables.
p <- ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width)) +
# Add points to the scatter plot using the `geom_point` function, with
# color representing different Species.
geom_point(aes(color = Species)) +
# Apply a minimal theme to the plot using the `theme_minimal`
# function, which removes most non-data ink from the plot.
theme_minimal() +
# Adjust the legend position to the bottom and remove the legend title
# using the `theme` function.
theme(legend.position = "bottom", legend.title = element_blank())

# Add marginal histograms to the scatter plot using the `ggMarginal`
# function, and set the `type` argument to `"density"` to create
# density plots instead of histograms. The `groupFill` argument is set
# to TRUE to fill the densities with different colors based on group
# (Species).
p_marginal <- ggMarginal(p, type = "density", groupFill = TRUE)

p_marginal # Display the plot.
```
```{r}
us_spending <- read_csv("data/USFR_StmtNetCost_2017_2022.csv") %>%
  janitor::clean_names() %>%
  filter((restatement_flag == "N") & (agency_name != "Total")) %>%
  select(year = statement_fiscal_year, agency_name, net_cost_in_billions) %>%
  mutate(net_cost_in_billions = as.numeric(net_cost_in_billions)) %>%
  group_by(year) %>%
  mutate(proportion = round(net_cost_in_billions / sum(net_cost_in_billions), 2)) %>%
  ungroup()

spending_plot_data <- us_spending %>%
  group_by(year) %>%
  mutate(rank = rank(-1 * net_cost_in_billions), agency = ifelse(rank >= 5, "Other", agency_name)) %>%
  count(year, agency, wt = net_cost_in_billions) %>%
  mutate(other = agency == "Other") %>%
  group_by(other) %>%
  arrange(desc(n), .by_group = T) %>%
  ungroup() %>%
  mutate(order = -1 * row_number()) %>%
  mutate(agency = recode(agency,
    "Department of Veterans Affairs" = "Vet. Affairs",
    "Department of Health and Human Services" = "HHS",
    "Department of Defense" = "Defense",
    "Social Security Administration" = "SSA",
    "Department of the Treasury" = "Treasury",
    "Interest on Treasury Securities Held by the Public" = "i on Treasuries"
  )) %>%
  mutate(agency = factor(agency, c("Other", "i on Treasuries", "Vet. Affairs", "Defense", "Treasury", "SSA", "HHS")))
```
```{r}
#| label: fig-stacked
stacked <- spending_plot_data %>%
  ggplot(aes(x = year, y = n, fill = agency, label = agency)) +
  geom_col(position = "stack", show.legend = F) +
  scale_fill_manual(values = c("#5E5E5E", "#EF3B2C", "#2CA25F", "#006837", "#F7DC6F", "#00FFFF", "#FFC0CB")) +
  geom_label(size = 2.8,
             aes(group = agency),
             position = position_stack(vjust = 0.5), fill = "white", 
             alpha = 0.5) +
  theme_minimal(base_size = 12) +
  theme(legend.position = "right",
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        plot.title.position = "plot"
        ) +
  labs(
    y = NULL,
    x = NULL,
    title = "US Expenditures Across Departments in $B by Year"
  ) +
  coord_cartesian(clip = "off") + 
  scale_x_continuous(expand = c(0,0.1), breaks = 2017:2022, labels = 2017:2022) +
  scale_y_continuous(expand = c(0, 0), label = scales::label_currency(scale =1/1000, accuracy = 1,suffix = "B")) 

stacked
ggsave("new_plots/fig-stacked.pdf", stacked,
       height = unit(3.5, "in"), width = unit(5, "in"))
```
```{r}
#| label: fig-stacked_prop
stacked_prop <- spending_plot_data %>%
  mutate(agency = factor(agency, c("Defense", "Other", "i on Treasuries", "Vet. Affairs", "Treasury", "HHS", "SSA"))) %>%
  ggplot(aes(x = year, y = n, fill = agency)) +
  geom_col(position = "fill", show.legend = T) +
  scale_fill_manual(
    values = c("#006837", "#5E5E5E", "#EF3B2C", "#2CA25F", "#F7DC6F", "#FFC0CB", "#00FFFF")
  ) +
  geom_label(aes(x = year, y = n,
                 label = agency, group = agency),
             size = 2.8,
             position = position_fill(vjust = 0.5),
             fill = "white",
             label.padding = unit(0.15, "lines"),
             alpha = 0.5) +
  theme_minimal(base_size = 12) +
  theme(legend.position = "none",
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        plot.title.position = "plot") +
  labs(
    y = NULL,
    x = NULL,
    title = "US Propotion Expenditures Across Departments"
  ) +
  coord_cartesian(clip = "off") +
  scale_x_continuous(expand = c(0,0.1),
                     breaks = 2017:2022,
                     labels = 2017:2022) +
  scale_y_continuous(expand = c(0, 0),
                     label = scales::label_percent())
stacked_prop
ggsave("new_plots/fig-stacked_prop.pdf", stacked_prop, height = unit(3.5, "in"), width = unit(5, "in"))
```
```{r}
japan_export <- read_csv("data/japan_export_2020.csv") %>%
  rename("export" = `Gross Export`) %>%
  janitor::clean_names()

japan_sectors <- japan_export %>% count(sector, wt = share)
```
```{r}
#| label: fig-pie
pie_1 <- japan_sectors %>%
  ggplot(aes(x = "", y = n, fill = sector)) +
  geom_bar(stat = "identity", width = 1) +
  theme_void() +
  theme(legend.position = "none")

pie_2 <- japan_sectors %>%
  ggplot(aes(x = "", y = n, fill = sector)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  theme(panel.background = element_rect(fill = "white"))

pie_1 + pie_2
```
```{r}
#| label: fig-pie_japan
japan_sectors %>%
  mutate(sector = ifelse(n < 11, "Other", sector)) %>%
  count(sector, wt = n) %>%
  mutate(other = sector == "Other") %>%
  group_by(other) %>%
  arrange(desc(n), .by_group = T) %>%
  ungroup() %>%
  mutate(prop = n / sum(japan_sectors$n) * 100) %>%
  mutate(ypos = cumsum(prop) - 0.5 * prop) %>%
  mutate(order = -1 * row_number()) %>%
  ggplot(aes(x = "", y = n, fill = fct_reorder(sector, order))) +
  geom_bar(
    stat = "identity", width = 1, color =
      "white"
  ) +
  coord_polar("y", start = 0) +
  theme_void() +
  theme(legend.position = "none") +
  geom_text(aes(y = ypos, label = sector), color = c("white", "#333333", rep("white", 4)), size = 6) +
  scale_fill_manual(values = c("grey", "#009E73", "#D55E00", "#CC79A7", "#F0E442", "#56B4E9"))
```
```{r}
#| label: fig-waffle

japan_sectors %>%

  mutate(sector = ifelse(n < 11, "Other", sector)) %>%
  mutate(other = sector == "Other") %>%
  uncount(weights = round(n, 0)) %>%
  group_by(other) %>%
  arrange(desc(n), .by_group = T) %>%
  ungroup() %>%
  waffle_iron(aes_d(group = sector)) %>%
  ggplot(aes(x, y, fill = group)) +
  geom_waffle() +
  coord_equal() +
  theme_waffle() +
  theme(legend.position = "top", legend.title = element_blank()) +
  labs(x = element_blank(), y = element_blank()) +
  scale_fill_manual(values = c(
    "#009E73",
    "#D55E00",
    "#56B4E9",
    "grey",
    "#F0E442",
    "#CC79A7"
    ))
```
```{r}
#| label: fig-treemap
library(treemap)
treemap(japan_export,
  index = c("sector", "name"),
  vSize = "export",
  type = "index",
  fontsize.labels = c(14, 10),
  fontcolor.labels = c("black", "white"),
  fontface.labels = c(2, 1),
  bg.labels = 0,
  align.labels = list(
    c("center", "center"),
    c("left", "top")
  ),
  border.col = c("black", "white"),
  border.lwds = c(3, 1),
  title = "Japans Export in 2020",
  fontsize.title = 14
)
```
```{r}
#| label: fig-scatter
scatter_1 <- iris %>%
  drop_na() %>%
  ggplot(aes(x = Sepal.Length, y = Sepal.Width, color = Species)) +
  geom_point(show.legend = F) +
  geom_dl(aes(label = Species), method = "smart.grid") +
  theme_minimal() +
  labs(x = "Sepal Length", y = "Sepal Width")

scatter_2 <- scatter_1 + geom_smooth(se = F, fullrange = F, show.legend = F, method = "lm", linewidth = 2) + theme(
  axis.title.y = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks.y = element_blank()
)

scatter_1 + scatter_2
```
```{r}
#| label: fig-correlograms
library(GGally)

correlogram <- GGally::ggpairs(
# Select the dataset for which to create a correlogram, in this case,
# the iris dataset.
iris,
# Map the color of points to the Species variable.
mapping = ggplot2::aes(color = Species),
# Disable the display of a progress bar during the plot's creation.
axisLabels = "none", 
progress = FALSE
) +
theme_minimal(base_size = 16)

# correlogram
correlogram
ggsave("new_plots/fig-correlogram.pdf", correlogram, height = unit(7,'in'), width = unit(8,'in'))
```
```{r}
sp500 <- tribble(
  ~Year, ~Average_Closing_Price, ~Year_Open, ~Year_High, ~Year_Low, ~Year_Close, ~Annual_Percent_Change,
  2023, 4020.94, 3824.14, 4179.76, 3808.10, 3970.04, 3.40,
  2022, 4097.49, 4796.56, 4796.56, 3577.03, 3839.50, -19.44,
  2021, 4273.41, 3700.65, 4793.06, 3700.65, 4766.18, 26.89,
  2020, 3217.86, 3257.85, 3756.07, 2237.40, 3756.07, 16.26,
  2019, 2913.36, 2510.03, 3240.02, 2447.89, 3230.78, 28.88,
  2018, 2746.21, 2695.81, 2930.75, 2351.10, 2506.85, -6.24,
  2017, 2449.08, 2257.83, 2690.16, 2257.83, 2673.61, 19.42,
  2016, 2094.65, 2012.66, 2271.72, 1829.08, 2238.83, 9.54,
  2015, 2061.07, 2058.20, 2130.82, 1867.61, 2043.94, -0.73,
  2014, 1931.38, 1831.98, 2090.57, 1741.89, 2058.90, 11.39,
  2013, 1643.80, 1462.42, 1848.36, 1457.15, 1848.36, 29.60,
  2012, 1379.61, 1277.06, 1465.77, 1277.06, 1426.19, 13.41,
  2011, 1267.64, 1271.87, 1363.61, 1099.23, 1257.60, 0.00,
  2010, 1139.97, 1132.99, 1259.78, 1022.58, 1257.64, 12.78,
  2009, 948.05, 931.80, 1127.78, 676.53, 1115.10, 23.45,
  2008, 1220.04, 1447.16, 1447.16, 752.44, 903.25, -38.49,
  2007, 1477.18, 1416.60, 1565.15, 1374.12, 1468.36, 3.53,
  2006, 1310.46, 1268.80, 1427.09, 1223.69, 1418.30, 13.62
)
```
```{r}
#| label: fig-line
sp500_scatter <- sp500 %>%
  select(-c(Average_Closing_Price, Year_Open, Annual_Percent_Change)) %>%
  pivot_longer(-Year) %>%
  mutate(year_close = name != "Year_Close") %>%
  ggplot(aes(x = Year, y = value, color = name)) +
  geom_point(size = 2) +
  geom_dl(aes(label = name), method = "smart.grid") +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(x = element_blank(), y = "S&P 500")

sp500_line <- sp500 %>%
  select(-c(Average_Closing_Price, Year_Open, Annual_Percent_Change)) %>%
  pivot_longer(-Year) %>%
  mutate(year_close = name != "Year_Close") %>%
  ggplot(aes(x = Year, y = value, color = name)) +
  geom_line(aes(linetype = year_close), linewidth = 1.5) +
  scale_color_manual(values = c("steelblue", "grey", "grey")) +
  geom_dl(aes(label = name), method = "smart.grid") +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(x = element_blank(), y = "S&P 500")

sp500_scatter + sp500_line
```
```{r}
#| label: fig-waterfall
waterfall_data <- tribble(
  ~year, ~bank, ~change,
  2017, 2000, 2000,
  2018, 1745, -255,
  2019, 1930, 185,
  2020, 2197, 267,
  2021, 2453, 256,
  2022, 2300, -153,
) %>% transmute(as.character(year), change)

library(waterfalls)

waterfall <- waterfall(waterfall_data,
  calc_total = TRUE,
  total_rect_color = "orange",
  total_rect_text_color = "black",rect_text_size = 3/.pt
) +
  theme_minimal(base_size = 12) +
  theme(panel.grid = element_blank()) +
  labs(y = "Money in Bank", x = NULL)

waterfall
ggsave("new_plots/fig-waterfall.pdf", waterfall, height = 2.5, width = 4)
```
